# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='thirdMenuOrder',
        ),
    ]
