# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_page_thirdmenuoeder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='thirdMenuOeder',
        ),
    ]
